service:
  name: lq-cognito-triggers${self:custom.${self:provider.stage}.branch}


frameworkVersion: ">=1.0.0 <2.0.0"

custom: ${file(../../../serverless-custom.yml)}

package:
  individually: true

provider:
  name: aws
  runtime: python3.8
  memorySize: 128
  timeout: 10
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.${self:provider.stage}.Stack}-restApiId-${self:provider.stage}${self:custom.${self:provider.stage}.branch}
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.${self:provider.stage}.Stack}-rootResourceId-${self:provider.stage}${self:custom.${self:provider.stage}.branch}
  CogUserPool:
    'Fn::ImportValue':  ${self:custom.${self:provider.stage}.Stack}-userpool-${self:provider.stage}${self:custom.${self:provider.stage}.branch}
  CogUserPoolArn:
    'Fn::ImportValue':  ${self:custom.${self:provider.stage}.Stack}-userpoolarn-${self:provider.stage}${self:custom.${self:provider.stage}.branch}
  environment:
    REGION: ${self:provider.region}
    LOG_LEVEL: ${self:custom.${self:provider.stage}.LogLevel}
    SECURED_URL_SECRET_KEY: "Ly8iepQDhuAHTyoi3B3cCq4mco"
    SECURITY_PASSWORD_SALT: "InVzuAHa21ZXJpZCIQDhuAHTyoi"


functions:
  PreSignUP:
    handler: pre_signup.handler
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource:
          - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.userTableName}
          - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.userTableName}/index/*
      - Effect: Allow
        Action:
          - 'cognito-idp:*'
        Resource: ${self:provider.CogUserPoolArn}
    environment:
      USERS_TABLE: ${self:custom.userTableName}
      USER_POOL_ID:
        'Fn::ImportValue': ${self:custom.${self:provider.stage}.Stack}-userpoolid-${self:provider.stage}${self:custom.${self:provider.stage}.branch}
    events:
      - cognitoUserPool:
          pool: ${self:provider.CogUserPool}
          trigger: PreSignUp
          existing: true
    layers:
      - ${cf:python-utils-${self:provider.stage}.PythonUtilsLambdaLayerQualifiedArn}

plugins:
  - serverless-python-requirements
  - serverless-wsgi
