class LocalConstants:
    INVALID_ROLE = "User does have valid role."
    USER_NOT_EXIST = "User does not exist with the given username."
    INVALID_DATE = "Invalid date is provided."
    INVALID_USER = "Invalid user."
    USER_PREFIX = "user#"
    USER = "user"
    CUSTOM_ROLE = "custom:role"
    USER_PROFILE_SK = "profile"
    DOCTOR_PREFIX = "d#"
    HASH = "#"
    STATUS = "status"
    DOCTOR_ID = "doctor_id"
    START_TIME = "start_time"
    PATIENT_ID = "patient_id"
    START_DATE = "start_date"
    DATE = "date"
    OPERATIONAL_HOURS = "operational_hours"
    CONSULTATION_SLOT = "consultation_slot"
    APT = "Appointments"
    TIME_FORMAT = "%H:%M:%S"
    DATE_FORMAT = "%Y-%m-%d"
    DATETIME_FORMAT = "%Y-%m-%dT%H:%M:%S"
    MIDNIGHT = "23:59:59"
    NEWDAY = "00:00:01"
    AVAILABLE_DATES = "Available dates"
    OPERATIONAL_DAYS = "operational_days"
    day_name = {0: "mon", 1: "tue", 2: "wed", 3: "thu", 4: "fri", 5: "sat", 6: "sun"}


class AptStatus:
    CONFIRMED = "Confirmed"
    RESCHEDULED = "Rescheduled"
    DOCTOR_CANCEL_REQUEST = "DoctorCancellationRequested"
    PATIENT_CANCEL_REQUEST = "PatientCancellationRequested"
    DOCTOR_CANCEL = "DoctorCancelled"
    PATIENT_CANCEL = "PatientCancelled"
    DOC_NO_SHOW = "DocNoShow"
    PAT_NO_SHOW = "PatNoShow"
    COMPLETED = "Completed"


class LocalUriPaths:
    GET_DOCTOR_DATES = "/users/<string:user_id>/availabledates"
    GET_USER_APTS = "/users/<string:user_id>/appointments"
    TEMP_USER_APTS = "/users/<string:user_id>/appointments/<string:date>"
    GET_AVAILABLE_SLOTS = "/users/<string:user_id>/availableslots"
    GET_USER = UPDATE_USER_PROFILE = "/users/<string:user_id>"
    SEARCH_USER = "/users/search"
    CREATE_USER = "/users"
