service:
  name: lq-s3-triggers${self:custom.${self:provider.stage}.branch}


frameworkVersion: ">=1.0.0 <2.0.0"

custom: ${file(../../../serverless-custom.yml)}

package:
  individually: true

provider:
  name: aws
  runtime: python3.8
  memorySize: 128
  timeout: 10
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.${self:provider.stage}.Stack}-restApiId-${self:provider.stage}${self:custom.${self:provider.stage}.branch}
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.${self:provider.stage}.Stack}-rootResourceId-${self:provider.stage}${self:custom.${self:provider.stage}.branch}
  CogUserPool:
    'Fn::ImportValue':  ${self:custom.${self:provider.stage}.Stack}-userpool-${self:provider.stage}${self:custom.${self:provider.stage}.branch}
  CogUserPoolArn:
    'Fn::ImportValue':  ${self:custom.${self:provider.stage}.Stack}-userpoolarn-${self:provider.stage}${self:custom.${self:provider.stage}.branch}
  environment:
    REGION: ${self:provider.region}
    LOG_LEVEL: ${self:custom.${self:provider.stage}.LogLevel}

functions:
  documentS3:
    handler: s3_trigger.handler
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:PutItem
          - dynamodb:UpdateItem
        Resource:
          - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.userTableName}
      - Effect: "Allow"
        Action:
          - s3:GetObject
        Resource:
          - arn:aws:s3:::${self:custom.DataBucketName}/*
    environment:
      USERS_TABLE: ${self:custom.userTableName}
    events:
      - s3:
          bucket: ${self:custom.DataBucketName}
          event: s3:ObjectCreated:*
          existing: true
    layers:
      - ${cf:python-utils-${self:provider.stage}.PythonUtilsLambdaLayerQualifiedArn}

plugins:
  - serverless-python-requirements
  - serverless-wsgi
